apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: flattrack
spec:
  images:
  - glob: "**"
  authorities:
  - keyless:
      identities:
      - issuer: https://gitlab.com
        subjectRegExp: "https://gitlab.com/flattrack/flattrack//.gitlab-ci.yml@.*"
