apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: kubernetes
spec:
  images:
  - glob: "**"
  authorities:
  - keyless:
      url: https://fulcio.sigstore.dev
      identities:
      - issuer: https://accounts.google.com
        subject: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
    ctlog:
      url: https://rekor.sigstore.dev
